version: '3'

services:
  backend:
    image: flaskappback
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    networks:
      - my-network

  frontend:
    image: flaskappfront
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      BACKEND_API_URL: "http://backend:5000/api"
    networks:
      - my-network

  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data: