version: '3'

services:
  flaskappback:
    build: ./backend
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    networks:
      - my-network

  flaskappfront:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      BACKEND_URL: http://flaskappback:5000
    networks:
      - my-network

  postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: username
        POSTGRES_PASSWORD: password
        POSTGRES_PORT: 5432
      ports:
        - "6000:5432"
      networks:
        - my-network

networks:
  my-network:
    driver: bridge